#+TITLE:Builiding LineageOS from source for LG-V20
#+DATE: [2020-05-11-0024]
#+KEYWORDS: #lineageos

* Reflection
I attempted to build [[https://en.wikipedia.org/wiki/LineageOS][LineageOS]] from source for the LG-V20. I used a Thinkpad X230 with 16GB of RAM and 500GB of storage as the main device I was using to build the image in a virtual machine. I installed the necessary packages for the building environment and created their respective directories. When I initialized the [[https://en.wikipedia.org/wiki/LineageOS][LineageOS]] repository by running:

#+BEGIN_SRC shell
repo init -u https://github.com/LineageOS/android.git -b lineage-17.1
#+END_SRC

I realized that I was downloading several gigabytes of data. According to the Android Open Source Project [[https://source.android.com/setup/build/requirements][requirements]] website it recommends:

#+BEGIN_QUOTE
At least 250GB of free disk space to check out the code and an extra 150 GB to build it. If you conduct multiple builds, you need additional space.

#+END_QUOTE

And in addition to this:
#+BEGIN_QUOTE
If you're running Linux in a virtual machine, you need at least 16 GB of RAM/swap.
#+END_QUOTE
I was stuck at the last stage of, "Start the build" for several hours and at the end I wasn't able to build the image. Everytime I attempted to run the command:
#+BEGIN_SRC shell
croot
brunch h918
#+END_SRC

I noticed in htop that ram usage would increase until it reached the maximum amount of ram I had allocated, and it would fail.

* Lessons
Going forward I'm thinking about using another machine possibly [[https://workstream.paperspace.com/][Workstream]] and or building my own machine preferably running [[https://www.coreboot.org/][Coreboot]] or a device from [[https://www.raptorcs.com/][Raptor Computing Systems]].

* Process
** Installing the platform tools
Installing the platform tools under Debian 10 Buster
#+BEGIN_SRC shell
sudo apt install android-tools-adb android-tools-fastboot
#+END_SRC

The platform tools are used to be able to communicate with the device, send/receive files/payloads and boot to certain modes to allow it to flash.

** Installing the necessary packages to build Lineage OS
#+BEGIN_SRC shell
sudo apt-get install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
#+END_SRC

For Ubuntu versions older than 20.04 (focal), install also:

libwxgtk3.0-dev

While for Ubuntu versions older than 16.04 (xenial), install:

libwxgtk2.8-dev

** Installing different versions of JDK(Java Development Kit) to install different versions of lineage
** Creating directories for build environment
The ~/bin directory will contain the git-repo tool (commonly named “repo”) and the ~/android/lineage directory will contain the source code of LineageOS.

#+BEGIN_SRC shell
mkdir -p ~/bin
mkdir -p ~/android/lineage
#+END_SRC

** Installing the repo command
I sourced ~/.profile to the environment
#+BEGIN_SRC shell
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
#+END_SRC

** Configured Git
repo commands require you to identify yourself to sync Android, we need to configure your your git identity:
#+BEGIN_SRC shell
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
#+END_SRC
** Initialize the LineageOS source repository
The following branches are officially supported for the LG V20 (T-Mobile):
cm-14.1
lineage-17.1

Enter the following to initialize the repository:
#+BEGIN_SRC shell
cd ~/android/lineage
repo init -u https://github.com/LineageOS/android.git -b lineage-17.1
#+END_SRC

** Downloading the source code
#+BEGIN_SRC shell
repo sync
#+END_SRC
The LineageOS manifests include a sensible default configuration for repo, which we strongly suggest you use (i.e. don’t add any options to sync). For reference, our default values are -j 4 and -c. The -j 4 part means that there will be four simultaneous threads/connections. If you experience problems syncing, you can lower this to -j 3 or -j 2. On the other hand, -c will ask repo to pull in only the current branch instead of all branches that are available on GitHub.

TIP: The repo sync command is used to update the latest source code from LineageOS and Google. Remember it, as you may want to do it every few days to keep your code base fresh and up-to-date.

** Prepare the device-specific code
After the source downloads, ensure you’re in the root of the source code (cd ~/android/lineage), then type:
#+BEGIN_SRC shell
source build/envsetup.sh
breakfast h918
#+END_SRC
This will download your device’s device specific configuration and kernel.
** Turn on caching to speed up build
Make use of ccache if you want to speed up subsequent builds by running:
#+BEGIN_SRC shell
export USE_CCACHE=1
export CCACHE_EXEC=/usr/bin/ccache
#+END_SRC
** Start the build
Time to start building! Now, type:
#+BEGIN_SRC shell
croot
brunch h918
#+END_SRC

* Related
* External Links
- [[https://wiki.lineageos.org/devices/h918/build][Build for h918 | LineageOS Wiki]]
- [[https://download.lineageos.org/h918][LineageOS Downloads]]
- [[https://source.android.com/setup/build/requirements][Requirements  |  Android Open Source Project]]
- [[https://www.raptorcs.com/][Raptor Computing Systems::Talos™ II]]
- [[https://www.coreboot.org/][coreboot]]
- [[https://workstream.paperspace.com/][Workstream Home]]
