#+TITLE:Builiding Lineage OS from source for LG-V20
#+DATE: [2020-05-11-0024]
#+KEYWORDS:

* Build LineageOS and LineageOS Recovery
** Installing the platform tools
Installing the platform tools under Debian 10 Buster
#+BEGIN_SRC shell
sudo apt install android-tools-adb android-tools-fastboot
#+END_SRC

The platform tools are used to be able to communicate with the device, send/receive files/payloads and boot to certain modes to allow it to flash.

** Installing the necessary packages to build Lineage OS
#+BEGIN_SRC shell
sudo apt-get install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
#+END_SRC

For Ubuntu versions older than 20.04 (focal), install also:

libwxgtk3.0-dev

While for Ubuntu versions older than 16.04 (xenial), install:

libwxgtk2.8-dev

** Installing different versions of JDK(Java Development Kit) to install different versions of lineage
** Creating directories for build environment
The ~/bin directory will contain the git-repo tool (commonly named “repo”) and the ~/android/lineage directory will contain the source code of LineageOS.

#+BEGIN_SRC shell
mkdir -p ~/bin
mkdir -p ~/android/lineage
#+END_SRC

** Installing the repo command
I sourced ~/.profile to the environment
#+BEGIN_SRC shell
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
#+END_SRC

** Configured Git
repo commands require you to identify yourself to sync Android, we need to configure your your git identity:
#+BEGIN_SRC shell
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
#+END_SRC
** Initialize the LineageOS source repository
The following branches are officially supported for the LG V20 (T-Mobile):
cm-14.1
lineage-17.1

Enter the following to initialize the repository:
#+BEGIN_SRC shell
cd ~/android/lineage
repo init -u https://github.com/LineageOS/android.git -b lineage-17.1
#+END_SRC

** Downloading the source code
#+BEGIN_SRC shell
repo sync
#+END_SRC
The LineageOS manifests include a sensible default configuration for repo, which we strongly suggest you use (i.e. don’t add any options to sync). For reference, our default values are -j 4 and -c. The -j 4 part means that there will be four simultaneous threads/connections. If you experience problems syncing, you can lower this to -j 3 or -j 2. On the other hand, -c will ask repo to pull in only the current branch instead of all branches that are available on GitHub.

TIP: The repo sync command is used to update the latest source code from LineageOS and Google. Remember it, as you may want to do it every few days to keep your code base fresh and up-to-date.

** Prepare the device-specific code
After the source downloads, ensure you’re in the root of the source code (cd ~/android/lineage), then type:
#+BEGIN_SRC shell
source build/envsetup.sh
breakfast h918
#+END_SRC
This will download your device’s device specific configuration and kernel.
** Turn on caching to speed up build
Make use of ccache if you want to speed up subsequent builds by running:
#+BEGIN_SRC shell
export USE_CCACHE=1
export CCACHE_EXEC=/usr/bin/ccache
#+END_SRC
** Start the build
Time to start building! Now, type:
#+BEGIN_SRC shell
croot
brunch h918
#+END_SRC


* Reflection


* Related
* External Links
[[https://wiki.lineageos.org/devices/h918/build][Build for h918 | LineageOS Wiki]]
